# Generated by Django 3.0.3 on 2020-11-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyModel',
            fields=[
                ('country', models.CharField(default='', max_length=2)),
                ('display_name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('href', models.CharField(default='', max_length=50)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
    ]
