# Generated by Django 3.1.2 on 2020-11-08 03:49


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.CharField(default='', max_length=70, primary_key=True, serialize=False)),
                ('country', models.CharField(default='', max_length=2)),
                ('display_name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('href', models.CharField(default='', max_length=50)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
    ]
