# Generated by Django 3.0.3 on 2020-11-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='access_token',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
