# Generated by Django 3.0.3 on 2020-11-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='access_token',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='image',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='spotifyuser',
            name='id',
            field=models.CharField(default='', max_length=70, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='SpotifyRecentlyPlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(default='', max_length=70)),
                ('artist_name', models.CharField(default='', max_length=70)),
                ('played_at', models.DateField()),
                ('track_id', models.CharField(default='', max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.SpotifyUser')),
            ],
        ),
    ]
