# Generated by Django 3.0.3 on 2020-11-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20201112_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyrecentlyplayed',
            name='track_id',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
