# Generated by Django 3.0.3 on 2020-11-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20201110_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuser',
            name='id',
            field=models.CharField(default='', max_length=70, primary_key=True, serialize=False, unique=True),
        ),
    ]
