# Generated by Django 3.0.3 on 2020-11-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20201111_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyrecentlyplayed',
            name='track_id',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
