# Generated by Django 3.0.3 on 2020-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_spotifyrecentlyplayed_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyrecentlyplayed',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='spotifyrecentlyplayed',
            name='preview_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='spotifyrecentlyplayed',
            name='track_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
