# Generated by Django 3.0.3 on 2020-11-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_auto_20201117_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='refresh_token',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
