# Generated by Django 3.0.3 on 2020-11-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_spotifyuser_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTopArtistsLongTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='', max_length=70)),
                ('image', models.CharField(default='', max_length=200)),
                ('artist_url', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.SpotifyUser')),
            ],
        ),
    ]
