# Generated by Django 3.0.3 on 2020-11-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_spotifytopartistslongterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytopartistslongterm',
            name='artist_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
