# Generated by Django 3.0.3 on 2020-12-01 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_spotifytopartistslongterm_artist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTopArtistsSHORTTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='', max_length=70)),
                ('image', models.CharField(default='', max_length=200)),
                ('artist_url', models.CharField(default='', max_length=200)),
                ('artist_id', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.SpotifyUser')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyTopArtistsMEDIUMTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(default='', max_length=70)),
                ('image', models.CharField(default='', max_length=200)),
                ('artist_url', models.CharField(default='', max_length=200)),
                ('artist_id', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.SpotifyUser')),
            ],
        ),
    ]
