# Generated by Django 3.0.5 on 2020-10-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=70, unique=True)),
                ('firstName', models.CharField(default='', max_length=70)),
                ('lastName', models.CharField(default='', max_length=70)),
                ('fullName', models.CharField(default='', max_length=70)),
                ('imageUrl', models.CharField(default='', max_length=200)),
                ('googleId', models.CharField(default='', max_length=70)),
                ('tokenId', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
