# Generated by Django 3.0.5 on 2020-10-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=70)),
                ('firstName', models.CharField(default='', max_length=70)),
                ('lastName', models.CharField(default='', max_length=70)),
                ('fullName', models.CharField(default='', max_length=70)),
                ('imageUrl', models.CharField(default='', max_length=200)),
                ('googleId', models.CharField(default='', max_length=70)),
                ('tokenId', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialApp',
        ),
    ]
