# Generated by Django 3.0.3 on 2020-11-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=70)),
                ('name', models.CharField(default='', max_length=70)),
                ('user_id', models.IntegerField(default=0)),
                ('screen_name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=1000)),
                ('followers_count', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('auth_token', models.CharField(default='', max_length=2000)),
                ('auth_token_secret', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
