# Generated by Django 3.0.3 on 2020-11-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterTopWorst',
            fields=[
                ('tweet_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=70)),
                ('screen_name', models.CharField(default='', max_length=70)),
                ('retweet_count', models.IntegerField(default=0, max_length=70)),
                ('text', models.CharField(default='', max_length=280)),
                ('favorite_count', models.IntegerField(default=0, max_length=70)),
                ('reply_count', models.IntegerField(default=0, max_length=70)),
                ('top_tweet', models.BooleanField(default=True)),
                ('twitter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.TwitterModel')),
            ],
        ),
    ]
