# Generated by Django 3.0.3 on 2020-11-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_twittertopworst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertopworst',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twittertopworst',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twittertopworst',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
    ]
