# Generated by Django 3.0.3 on 2020-11-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20201109_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twittertopworst',
            old_name='twitter_id',
            new_name='user_twitter_id',
        ),
    ]
