# Generated by Django 3.0.3 on 2020-11-09 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_auto_20201109_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittertopworst',
            name='reply_count',
        ),
    ]
