# Generated by Django 3.0.3 on 2020-11-09 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20201109_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twittertopworst',
            old_name='tweet_index',
            new_name='tweet_position',
        ),
    ]
