# Generated by Django 3.0.3 on 2020-11-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20201109_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittertopworst',
            name='tweet_position',
        ),
        migrations.AddField(
            model_name='twittertopworst',
            name='top_tweet',
            field=models.BooleanField(default=True),
        ),
    ]
