# Generated by Django 3.0.3 on 2020-11-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_remove_twittertopworst_user_twitter_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterTopWorst',
        ),
    ]
