// Auth
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESSFULLY'

export const VERIFY_GOOGLE_TOKEN_SUCCESS = 'VERIFY_GOOGLE_TOKEN_SUCCESS'
export const VERIFY_GOOGLE_TOKEN_FAILED = 'VERIFY_GOOGLE_TOKEN_FAILED'

export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESSFULLY'

export const SET_USER_INFO = 'SET_USER_INFO'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

export const LOGOUT = 'LOGOUT'

// Spotify
export const SPOTIFY_AUTH_SUCCESS = 'SPOTIFY_AUTH_SUCCESS'
export const SPOTIFY_AUTH_FAILED = 'SPOTIFY_AUTH_FAILED'

export const SPOTIFY_GET_USER_SUCCESS = 'SPOTIFY_GET_USER_SUCCESS'
export const SPOTIFY_GET_USER_FAILED = 'SPOTIFY_GET_USER_FAILED'

export const SPOTIFY_GET_TOP_TRACKS_SUCCESS = 'SPOTIFY_GET_TOP_TRACKS_SUCCESS'
export const SPOTIFY_GET_TOP_TRACKS_FAILED = 'SPOTIFY_GET_TOP_TRACKS_FAILED'

export const SPOTIFY_GET_TOP_PLAYLISTS_SUCCESS =
  'SPOTIFY_GET_TOP_PLAYLISTS_SUCCESS'
export const SPOTIFY_GET_TOP_PLAYLISTS_FAILED =
  'SPOTIFY_GET_TOP_PLAYLISTS_FAILED'

// Twitter
export const TWITTER_AUTH_SUCCESS = 'TWITTER_AUTH_SUCCESS'
export const TWITTER_AUTH_FAILED = 'TWITTER_AUTH_FAILED'

export const TWITTER_ACCESS_TOKEN_SUCCESS = 'TWITTER_ACCESS_TOKEN_SUCCESS'
export const TWITTER_ACCESS_TOKEN_FAILED = 'TWITTER_ACCESS_TOKEN_FAILED'

export const TWITTER_GET_USER_SUCCESS = 'TWITTER_GET_USER_SUCCESS'
export const TWITTER_GET_USER_FAILED = 'TWITTER_GET_USER_FAILED'

export const TWITTER_TOP_WORST_TWEETS_SUCCESS =
  'TWITTER_TOP_WORST_TWEETS_SUCCESS'
export const TWITTER_TOP_WORST_TWEETS_FAILED = 'TWITTER_TOP_WORST_TWEETS_FAILED'

export const TWITTER_GET_TOP_WORST_TWEETS_SUCCESS =
  'GET_TOP_WORST_TWEETS_SUCCESS'
export const TWITTER_GET_TOP_WORST_TWEETS_FAILED = 'GET_TOP_WORST_TWEETS_FAILED'
