// Auth
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESSFULLY'

export const VERIFY_GOOGLE_TOKEN_SUCCESS = 'VERIFY_GOOGLE_TOKEN_SUCCESS'
export const VERIFY_GOOGLE_TOKEN_FAILED = 'VERIFY_GOOGLE_TOKEN_FAILED'

export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESSFULLY'

export const SET_USER_INFO = 'SET_USER_INFO'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

export const LOGOUT = 'LOGOUT'

// Spotify

// Twitter
